FROM node:18-alpine

WORKDIR /app

# Install deps
COPY frontend/package*.json ./
RUN npm install --production=false

# Copy source and build
COPY frontend/ .
RUN npm run build

ENV NODE_ENV=production
EXPOSE 3000
CMD ["npm", "run", "start"]
